"""Add seeking_talent & seeking_description to Venue

Revision ID: 91ec76153f42
Revises: 7220952ca667
Create Date: 2020-07-12 22:46:43.048507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ec76153f42'
down_revision = '7220952ca667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE "Venue" SET seeking_talent=False WHERE seeking_talent is NULL')

    op.alter_column('Venue', 'seeking_talent', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
